### ISSUE TITLE
the dataset 

### ISSUE THREAD

**Issue by Mrlong12** [ChunbiaoZhu/PDNet#1]
The Dataset RGBD135 depth map is black

**Comment by ChunbiaoZhu** [comment]
You should normalize the depth map of the RGBD135 dataset.

**Comment by Mrlong12** [comment]
thanks,And how normalize the depth map? my method is  depth = (depth.float() - depth.min().float())/(depth.max().float() - depth.min().float()) . but my network not show good.and my network work well in others dataset.

**Comment by ChunbiaoZhu** [comment]
Hi, please reverse the depth map to see the results.

**Comment by Mrlong12** [comment]
我翻转效果依然不好，当我深度map全都设为1的时候效果最好，就是将深度图以convert('L')打开的时候。请问他之前很大的depth map用很大的数也是代表深度？爲什麽別的数据集深度图都是0-1，这个数据集深度表达方式不一样？

**Comment by ChunbiaoZhu** [comment]
取反深度图试试，数值没什么关系。该数据集基本全是室内场景的图片，所以你的网络可能不太适用。

**Comment by Mrlong12** [comment]
取反是指数值取负号？还是将深度图翻转？

**Comment by ChunbiaoZhu** [comment]
正则化后，赋值1-value（‘depth map’）

**Comment by Mrlong12** [comment]
喔喔，非常感谢大神。

**Comment by Mrlong12** [comment]
Hi，thank you very much.I work well in the RGBD135 dataset as you say. And i have other question in stereo dataset. the depth map is like that.
![image](https://user-images.githubusercontent.com/43989375/57186561-10006080-6f14-11e9-802f-684eb10cdbc5.png)
and its depth value is like that.
![image](https://user-images.githubusercontent.com/43989375/57186591-65d50880-6f14-11e9-9352-edf13de7cf79.png)
its depth value cann't distinguish.Do you know how to solve the problem ？

**Comment by ChunbiaoZhu** [comment]
sorry, I didn't use the stereo dataset, so I don't know its attributes.
